Repository team-root/ROOT_BE, pull requests merged in 2025-01, with the labels that each got.

#4 merge: (#3) Dockerfile 추가
  Dockerfile
Labels: chore

#6 merge: (#5) auth개발
  build.gradle.kts
  src/main/kotlin/org/example/root_be/RootBeApplication.kt
  src/main/kotlin/org/example/root_be/domain/auth/domain/RefreshToken.kt
  src/main/kotlin/org/example/root_be/domain/auth/domain/repository/RefreshTokenRepository.kt
  src/main/kotlin/org/example/root_be/domain/auth/exception/InvalidRoleException.kt
  src/main/kotlin/org/example/root_be/domain/auth/exception/RefreshTokenNotFoundException.kt
  src/main/kotlin/org/example/root_be/domain/auth/presentation/AuthController.kt
  src/main/kotlin/org/example/root_be/domain/auth/presentation/dto/request/LoginRequest.kt
  src/main/kotlin/org/example/root_be/domain/auth/presentation/dto/request/RefreshRequest.kt
  src/main/kotlin/org/example/root_be/domain/auth/presentation/dto/response/LoginResponse.kt
  src/main/kotlin/org/example/root_be/domain/auth/presentation/dto/response/RefreshResponse.kt
  src/main/kotlin/org/example/root_be/domain/auth/service/LoginService.kt
  src/main/kotlin/org/example/root_be/domain/auth/service/RefreshService.kt
  src/main/kotlin/org/example/root_be/domain/user/domain/User.kt
  src/main/kotlin/org/example/root_be/domain/user/domain/repository/UserRepository.kt
  src/main/kotlin/org/example/root_be/domain/user/domain/type/Role.kt
  src/main/kotlin/org/example/root_be/domain/user/exception/UserNotFoundException.kt
  src/main/kotlin/org/example/root_be/domain/user/facade/UserFacade.kt
  src/main/kotlin/org/example/root_be/global/config/FilterConfig.kt
  src/main/kotlin/org/example/root_be/global/config/RedisConfig.kt
  src/main/kotlin/org/example/root_be/global/config/SecurityConfig.kt
  src/main/kotlin/org/example/root_be/global/config/WebConfig.kt
  src/main/kotlin/org/example/root_be/global/err/ErrorResponse.kt
  src/main/kotlin/org/example/root_be/global/err/GlobalExceptionFilter.kt
  src/main/kotlin/org/example/root_be/global/err/GlobalExceptionHandler.kt
  src/main/kotlin/org/example/root_be/global/err/exception/CustomException.kt
  src/main/kotlin/org/example/root_be/global/err/exception/ErrorCode.kt
  src/main/kotlin/org/example/root_be/global/security/auth/AuthDetails.kt
  src/main/kotlin/org/example/root_be/global/security/auth/AuthDetailsService.kt
  src/main/kotlin/org/example/root_be/global/security/jwt/JwtFilter.kt
  src/main/kotlin/org/example/root_be/global/security/jwt/JwtProperties.kt
  src/main/kotlin/org/example/root_be/global/security/jwt/JwtTokenProvider.kt
  src/main/kotlin/org/example/root_be/infrastructure/openfeign/FeignClientErrorDecoder.kt
  src/main/kotlin/org/example/root_be/infrastructure/openfeign/FeignConfig.kt
  src/main/kotlin/org/example/root_be/infrastructure/openfeign/client/DsmAuthClient.kt
  src/main/kotlin/org/example/root_be/infrastructure/openfeign/client/dto/request/UserInfoRequest.kt
  src/main/kotlin/org/example/root_be/infrastructure/openfeign/client/dto/response/UserInfoResponse.kt
  src/main/kotlin/org/example/root_be/infrastructure/openfeign/client/exception/FeignBadRequestException.kt
  src/main/kotlin/org/example/root_be/infrastructure/openfeign/client/exception/FeignServerException.kt
  src/main/resources/application.yml
Labels: feat

#9 merge: (#8) 권한별 API 접근 제어 추가
  src/main/kotlin/org/example/root_be/global/config/SecurityConfig.kt
Labels: chore

#13 refactor: (#12) API 권한별 접근 경로 수정
  src/main/kotlin/org/example/root_be/global/config/SecurityConfig.kt
Labels: chore

#11 merge: (#10) 마이페이지 조회 기능 추가
  src/main/kotlin/org/example/root_be/domain/user/presentation/UserController.kt
  src/main/kotlin/org/example/root_be/domain/user/presentation/dto/response/MypageResponse.kt
  src/main/kotlin/org/example/root_be/domain/user/service/MypageService.kt
Labels: feat

#19 merge: (#18) API 권한 설정 수정
  src/main/kotlin/org/example/root_be/global/config/SecurityConfig.kt
Labels: chore

#21 merge: 학생 목록 조회 구현
  src/main/kotlin/org/example/root_be/domain/user/presentation/UserController.kt
  src/main/kotlin/org/example/root_be/domain/user/presentation/dto/response/StudentElement.kt
  src/main/kotlin/org/example/root_be/domain/user/presentation/dto/response/StudentQueryResponse.kt
  src/main/kotlin/org/example/root_be/domain/user/service/StudentQueryService.kt
Labels: feat

#23 merge: 봉사 게시물 목록 조회 기능 구현
  src/main/kotlin/org/example/root_be/domain/volunteer/domain/repository/VolunteerPostRepository.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/presentation/VolunteerController.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/presentation/dto/request/ApplicationPeriodElement.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/presentation/dto/request/GenerateVolunteerPostRequest.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/presentation/dto/request/RoleElement.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/presentation/dto/request/WorkDateElement.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/presentation/dto/response/GetVolunteerPostsResponse.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/service/GenerateVolunteerPostService.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/service/GetVolunteerPostsService.kt
Labels: feat

#25 merge: 봉사 게시물 상세 조회 기능 개발
  src/main/kotlin/org/example/root_be/domain/volunteer/domain/VolunteerPost.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/exception/VolunteerPostNotFoundException.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/facade/VolunteerFacade.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/presentation/VolunteerController.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/presentation/dto/response/GetVolunteerPostResponse.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/service/GetVolunteerPostDetailsService.kt
  src/main/kotlin/org/example/root_be/domain/volunteer/service/GetVolunteerPostListService.kt
  src/main/kotlin/org/example/root_be/global/err/exception/ErrorCode.kt
Labels: feat

#28 merge: 내 봉사활동 조회 기능 구현
  src/main/kotlin/org/example/root_be/domain/activity/domain/VolunteerActivity.kt
  src/main/kotlin/org/example/root_be/domain/activity/domain/repository/VolunteerActivityRepository.kt
  src/main/kotlin/org/example/root_be/domain/user/presentation/UserController.kt
  src/main/kotlin/org/example/root_be/domain/user/presentation/dto/response/MyVolunteerActivityResponse.kt
  src/main/kotlin/org/example/root_be/domain/user/presentation/dto/response/VolunteerElement.kt
  src/main/kotlin/org/example/root_be/domain/user/service/MyVolunteerActivityService.kt
Labels: feat

#31 merge: 봉사 신청 API 구현
  src/main/kotlin/org/example/root_be/domain/applications/domain/VolunteerApplication.kt
  src/main/kotlin/org/example/root_be/domain/applications/domain/repository/VolunteerApplicationRepository.kt
  src/main/kotlin/org/example/root_be/domain/applications/presentation/ApplicationsController.kt
  src/main/kotlin/org/example/root_be/domain/applications/presentation/dto/response/ApplyVolunteerResponse.kt
  src/main/kotlin/org/example/root_be/domain/applications/service/ApplyVolunteerService.kt
Labels: feat

#33 merge: 패키지 리팩토링
  src/main/kotlin/org/example/root_be/domain/activity/domain/VolunteerActivity.kt
  src/main/kotlin/org/example/root_be/domain/applications/domain/VolunteerApplication.kt
  src/main/kotlin/org/example/root_be/domain/applications/service/ApplyVolunteerService.kt
  src/main/kotlin/org/example/root_be/domain/post/domain/VolunteerPost.kt
  src/main/kotlin/org/example/root_be/domain/post/domain/repository/VolunteerPostRepository.kt
  src/main/kotlin/org/example/root_be/domain/post/exception/VolunteerPostNotFoundException.kt
  src/main/kotlin/org/example/root_be/domain/post/facade/VolunteerFacade.kt
  src/main/kotlin/org/example/root_be/domain/post/presentation/VolunteerController.kt
  src/main/kotlin/org/example/root_be/domain/post/presentation/dto/request/GenerateVolunteerPostRequest.kt
  src/main/kotlin/org/example/root_be/domain/post/presentation/dto/response/GetVolunteerPostResponse.kt
  src/main/kotlin/org/example/root_be/domain/post/presentation/dto/response/GetVolunteerPostsResponse.kt
  src/main/kotlin/org/example/root_be/domain/post/service/GenerateVolunteerPostService.kt
  src/main/kotlin/org/example/root_be/domain/post/service/GetVolunteerPostDetailsService.kt
  src/main/kotlin/org/example/root_be/domain/post/service/GetVolunteerPostListService.kt
  src/main/kotlin/org/example/root_be/domain/role/domain/VolunteerRole.kt
  src/main/kotlin/org/example/root_be/domain/role/domain/repository/RoleRepository.kt
Labels: refactor

#35 merge: 봉사 신청 목록 조회 기능 추가
  src/main/kotlin/org/example/root_be/domain/applications/domain/repository/VolunteerApplicationRepository.kt
  src/main/kotlin/org/example/root_be/domain/applications/presentation/ApplicationsController.kt
  src/main/kotlin/org/example/root_be/domain/applications/presentation/dto/response/ApplicationElement.kt
  src/main/kotlin/org/example/root_be/domain/applications/presentation/dto/response/GetVolunteerApplicationResponse.kt
  src/main/kotlin/org/example/root_be/domain/applications/service/GetVolunteerApplicationService.kt
Labels: feat

#37 merge: 학생 봉사활동 조회 API 추가
  src/main/kotlin/org/example/root_be/domain/user/presentation/UserController.kt
  src/main/kotlin/org/example/root_be/domain/user/presentation/dto/response/StudentVolunteerActivityResponse.kt
  src/main/kotlin/org/example/root_be/domain/user/service/StudentVolunteerActivityService.kt
Labels: feat

#40 feat: (#38) 봉사 신청 수락/거절 기능 추가
  src/main/kotlin/org/example/root_be/domain/applications/exception/ApplicationNotFoundException.kt
  src/main/kotlin/org/example/root_be/domain/applications/facade/VolunteerApplicationFacade.kt
  src/main/kotlin/org/example/root_be/domain/applications/presentation/ApplicationsController.kt
  src/main/kotlin/org/example/root_be/domain/applications/presentation/dto/request/ProcessVolunteerApplicationRequest.kt
  src/main/kotlin/org/example/root_be/domain/applications/service/ProcessVolunteerApplicationService.kt
  src/main/kotlin/org/example/root_be/global/config/SecurityConfig.kt
  src/main/kotlin/org/example/root_be/global/err/exception/ErrorCode.kt
Labels: feat

#41 merge: 학생 봉사활동 기록 추가 API 구현
  src/main/kotlin/org/example/root_be/domain/activity/domain/VolunteerActivity.kt
  src/main/kotlin/org/example/root_be/domain/detail/domain/VolunteerDetail.kt
  src/main/kotlin/org/example/root_be/domain/detail/domain/repository/VolunteerDetailRepository.kt
  src/main/kotlin/org/example/root_be/domain/user/domain/User.kt
  src/main/kotlin/org/example/root_be/domain/user/domain/repository/UserRepository.kt
  src/main/kotlin/org/example/root_be/domain/user/facade/UserFacade.kt
  src/main/kotlin/org/example/root_be/domain/user/presentation/UserController.kt
  src/main/kotlin/org/example/root_be/domain/user/presentation/dto/request/AddStudentVolunteerRecordRequest.kt
  src/main/kotlin/org/example/root_be/domain/user/service/AddStudentVolunteerRecordService.kt
  src/main/kotlin/org/example/root_be/domain/user/service/MyVolunteerActivityService.kt
  src/main/kotlin/org/example/root_be/domain/user/service/StudentVolunteerActivityService.kt
Labels: feat

#44 merge: 봉사 게시물 수정 기능 개발
  src/main/kotlin/org/example/root_be/domain/post/domain/VolunteerPost.kt
  src/main/kotlin/org/example/root_be/domain/post/presentation/VolunteerController.kt
  src/main/kotlin/org/example/root_be/domain/post/presentation/dto/request/ModifyVolunteerPostRequest.kt
  src/main/kotlin/org/example/root_be/domain/post/service/ModifyVolunteerPostService.kt
  src/main/kotlin/org/example/root_be/domain/role/domain/VolunteerRole.kt
  src/main/kotlin/org/example/root_be/domain/role/domain/repository/RoleRepository.kt
  src/main/kotlin/org/example/root_be/domain/role/exception/VolunteerRoleNotFoundException.kt
  src/main/kotlin/org/example/root_be/global/err/exception/ErrorCode.kt
Labels: feat

#46 merge: VolunteerPost 엔티티 관련 로직 리팩토링
  src/main/kotlin/org/example/root_be/domain/detail/domain/VolunteerDetail.kt
  src/main/kotlin/org/example/root_be/domain/detail/exception/VolunteerDetailNotFoundException.kt
  src/main/kotlin/org/example/root_be/domain/detail/facade/DetailFacade.kt
  src/main/kotlin/org/example/root_be/domain/post/domain/VolunteerPost.kt
  src/main/kotlin/org/example/root_be/domain/post/presentation/dto/response/GetVolunteerPostResponse.kt
  src/main/kotlin/org/example/root_be/domain/post/service/GenerateVolunteerPostService.kt
  src/main/kotlin/org/example/root_be/domain/post/service/GetVolunteerPostDetailsService.kt
  src/main/kotlin/org/example/root_be/domain/post/service/ModifyVolunteerPostService.kt
  src/main/kotlin/org/example/root_be/global/err/exception/ErrorCode.kt
Labels: refactor

#48 feat: (#42) QR 코드 생성 기능 추가
  src/main/kotlin/org/example/root_be/domain/qrcode/domain/QrCode.kt
  src/main/kotlin/org/example/root_be/domain/qrcode/domain/repository/QrCodeRepository.kt
  src/main/kotlin/org/example/root_be/domain/qrcode/presentation/QRCodeController.kt
  src/main/kotlin/org/example/root_be/domain/qrcode/presentation/dto/request/GenerateQRCodeRequest.kt
  src/main/kotlin/org/example/root_be/domain/qrcode/presentation/dto/response/GenerateQRCodeResponse.kt
  src/main/kotlin/org/example/root_be/domain/qrcode/service/GenerateQRCodeService.kt
Labels: feat

#49 봉사 게시물 삭제 기능 개발
  src/main/kotlin/org/example/root_be/domain/post/domain/VolunteerPost.kt
  src/main/kotlin/org/example/root_be/domain/post/presentation/VolunteerController.kt
  src/main/kotlin/org/example/root_be/domain/post/service/DeleteVolunteerPostService.kt
  src/main/kotlin/org/example/root_be/domain/post/service/GenerateVolunteerPostService.kt
Labels: feat

#51 일정 추가 기능 개발
  src/main/kotlin/org/example/root_be/domain/schedule/domain/Schedule.kt
  src/main/kotlin/org/example/root_be/domain/schedule/domain/repository/ScheduleRepository.kt
  src/main/kotlin/org/example/root_be/domain/schedule/presentation/ScheduleController.kt
  src/main/kotlin/org/example/root_be/domain/schedule/presentation/dto/request/GenerateScheduleRequest.kt
  src/main/kotlin/org/example/root_be/domain/schedule/service/GenerateScheduleService.kt
Labels: feat

#53 merge: QR 코드 스캔 기능 추가
  src/main/kotlin/org/example/root_be/domain/qrcode/domain/repository/QrCodeRepository.kt
  src/main/kotlin/org/example/root_be/domain/qrcode/presentation/QRCodeController.kt
  src/main/kotlin/org/example/root_be/domain/qrcode/presentation/dto/request/ScanQRCodeRequest.kt
  src/main/kotlin/org/example/root_be/domain/qrcode/presentation/dto/response/ScanQRCodeResponse.kt
  src/main/kotlin/org/example/root_be/domain/qrcode/service/ScanQRCodeService.kt
Labels: feat
