Repository team-root/ROOT_BE, pull requests merged in 2025-02, with the labels that each got.

#56 merge: Schedule 엔티티 리팩토링 및 로직 수정
  src/main/kotlin/org/example/root_be/domain/schedule/domain/Schedule.kt
  src/main/kotlin/org/example/root_be/domain/schedule/domain/repository/ScheduleRepository.kt
  src/main/kotlin/org/example/root_be/domain/schedule/presentation/dto/response/GetScheduleListResponse.kt
  src/main/kotlin/org/example/root_be/domain/schedule/service/GenerateScheduleService.kt
  src/main/kotlin/org/example/root_be/domain/schedule/service/GetScheduleListService.kt
Labels: refactor

#59 merge: Add .dockerignore file for optimized docker build
  .dockerignore
Labels: chore

#61 merge: Optimize Dockerfile with no-daemon option and layer caching
  Dockerfile
Labels: refactor

#63 merge: Update base Docker image to eclipse-temurin 17
  Dockerfile
Labels: refactor

#64 merge: 봉사 일정 상세 조회 기능 개발
  src/main/kotlin/org/example/root_be/domain/schedule/domain/repository/ScheduleRepository.kt
  src/main/kotlin/org/example/root_be/domain/schedule/exception/ScheduleNotFoundException.kt
  src/main/kotlin/org/example/root_be/domain/schedule/facade/ScheduleFacade.kt
  src/main/kotlin/org/example/root_be/domain/schedule/presentation/ScheduleController.kt
  src/main/kotlin/org/example/root_be/domain/schedule/presentation/dto/response/GetScheduleResponse.kt
  src/main/kotlin/org/example/root_be/domain/schedule/service/GetScheduleService.kt
  src/main/kotlin/org/example/root_be/global/err/exception/ErrorCode.kt
Labels: feat

#66 봉사 일정 수정 기능 개발
  src/main/kotlin/org/example/root_be/domain/schedule/domain/Schedule.kt
  src/main/kotlin/org/example/root_be/domain/schedule/presentation/ScheduleController.kt
  src/main/kotlin/org/example/root_be/domain/schedule/presentation/dto/request/ModifyScheduleRequest.kt
  src/main/kotlin/org/example/root_be/domain/schedule/service/ModifyScheduleService.kt
Labels: feat

#68 봉사 일정 삭제 기능 개발
  src/main/kotlin/org/example/root_be/domain/schedule/presentation/ScheduleController.kt
  src/main/kotlin/org/example/root_be/domain/schedule/service/DeleteScheduleService.kt
Labels: feat

#70 봉사 역할 할당 기능 개발
  src/main/kotlin/org/example/root_be/domain/role/presentation/RoleController.kt
  src/main/kotlin/org/example/root_be/domain/role/presentation/dto/request/GranRoleRequest.kt
  src/main/kotlin/org/example/root_be/domain/role/service/GrantRoleService.kt
  src/main/kotlin/org/example/root_be/domain/user/domain/User.kt
Labels: feat

#72 알림 생성 기능 개발
  .gitignore
  build.gradle.kts
  src/main/kotlin/org/example/root_be/domain/auth/presentation/dto/request/LoginRequest.kt
  src/main/kotlin/org/example/root_be/domain/auth/service/LoginService.kt
  src/main/kotlin/org/example/root_be/domain/fcm/FcmMessage.kt
  src/main/kotlin/org/example/root_be/domain/fcm/service/FirebaseCloudMessageService.kt
  src/main/kotlin/org/example/root_be/domain/notification/domain/Notification.kt
  src/main/kotlin/org/example/root_be/domain/notification/domain/repository/NotificationRepository.kt
  src/main/kotlin/org/example/root_be/domain/notification/presentation/NotificationController.kt
  src/main/kotlin/org/example/root_be/domain/notification/presentation/dto/request/generateNotificationRequest.kt
  src/main/kotlin/org/example/root_be/domain/user/domain/User.kt
Labels: feat

#74 알림 조회 기능 개발
  src/main/kotlin/org/example/root_be/domain/notification/domain/repository/NotificationRepository.kt
  src/main/kotlin/org/example/root_be/domain/notification/presentation/NotificationController.kt
  src/main/kotlin/org/example/root_be/domain/notification/presentation/dto/response/GetNotificationListResponse.kt
  src/main/kotlin/org/example/root_be/domain/notification/service/GetNotificationListService.kt
Labels: feat

#76 feat: 마이페이지 API 구현
  src/main/kotlin/org/example/root_be/domain/applications/domain/VolunteerApplication.kt
  src/main/kotlin/org/example/root_be/domain/applications/domain/repository/VolunteerApplicationRepository.kt
  src/main/kotlin/org/example/root_be/domain/role/service/GrantRoleService.kt
  src/main/kotlin/org/example/root_be/domain/teacher_role/domain/TeacherRole.kt
  src/main/kotlin/org/example/root_be/domain/user/domain/User.kt
  src/main/kotlin/org/example/root_be/domain/user/presentation/dto/response/MypageResponse.kt
  src/main/kotlin/org/example/root_be/domain/user/service/MypageService.kt
Labels: refactor

#78 merge: TeacherRoleRepository 추가
  src/main/kotlin/org/example/root_be/domain/teacher_role/domain/repository/TeacherRoleRepository.kt
Labels: feat

#82 refactor: (#81) 전체적인 코드 리팩토링
  src/main/kotlin/org/example/root_be/domain/applications/presentation/ApplicationsController.kt
  src/main/kotlin/org/example/root_be/domain/applications/presentation/dto/request/ProcessVolunteerApplicationRequest.kt
  src/main/kotlin/org/example/root_be/domain/applications/service/ApplyVolunteerService.kt
  src/main/kotlin/org/example/root_be/domain/applications/service/GetVolunteerApplicationService.kt
  src/main/kotlin/org/example/root_be/domain/auth/presentation/AuthController.kt
  src/main/kotlin/org/example/root_be/domain/auth/presentation/dto/request/LoginRequest.kt
  src/main/kotlin/org/example/root_be/domain/auth/presentation/dto/request/RefreshRequest.kt
  src/main/kotlin/org/example/root_be/domain/auth/service/LoginService.kt
  src/main/kotlin/org/example/root_be/domain/fcm/presentation/dto/FcmMessage.kt
  src/main/kotlin/org/example/root_be/domain/fcm/service/FirebaseCloudMessageService.kt
  src/main/kotlin/org/example/root_be/domain/notification/presentation/NotificationController.kt
  src/main/kotlin/org/example/root_be/domain/post/domain/VolunteerPost.kt
  src/main/kotlin/org/example/root_be/domain/post/facade/VolunteerPostFacade.kt
  src/main/kotlin/org/example/root_be/domain/post/presentation/VolunteerPostController.kt
  src/main/kotlin/org/example/root_be/domain/post/presentation/dto/request/GenerateVolunteerPostRequest.kt
  src/main/kotlin/org/example/root_be/domain/post/presentation/dto/response/GetVolunteerPostResponse.kt
  src/main/kotlin/org/example/root_be/domain/post/service/DeleteVolunteerPostService.kt
  src/main/kotlin/org/example/root_be/domain/post/service/GenerateVolunteerPostService.kt
  src/main/kotlin/org/example/root_be/domain/post/service/GetVolunteerPostDetailsService.kt
  src/main/kotlin/org/example/root_be/domain/post/service/ModifyVolunteerPostService.kt
  src/main/kotlin/org/example/root_be/domain/post_day/domain/repository/PostDayRepository.kt
  src/main/kotlin/org/example/root_be/domain/post_day/exception/PostDayNotFoundException.kt
  src/main/kotlin/org/example/root_be/domain/qrcode/presentation/QRCodeController.kt
  src/main/kotlin/org/example/root_be/domain/qrcode/service/GenerateQRCodeService.kt
  src/main/kotlin/org/example/root_be/domain/role/domain/VolunteerRole.kt
  src/main/kotlin/org/example/root_be/domain/role/presentation/RoleController.kt
  src/main/kotlin/org/example/root_be/domain/role/service/GrantRoleService.kt
  src/main/kotlin/org/example/root_be/domain/schedule/presentation/ScheduleController.kt
  src/main/kotlin/org/example/root_be/domain/schedule/service/GetScheduleListService.kt
  src/main/kotlin/org/example/root_be/domain/user/domain/User.kt
  src/main/kotlin/org/example/root_be/domain/user/exception/UserNotFoundException.kt
  src/main/kotlin/org/example/root_be/domain/user/facade/UserFacade.kt
  src/main/kotlin/org/example/root_be/domain/user/presentation/UserController.kt
  src/main/kotlin/org/example/root_be/domain/user/presentation/dto/request/AddStudentVolunteerRecordRequest.kt
  src/main/kotlin/org/example/root_be/domain/user/service/MypageService.kt
  src/main/kotlin/org/example/root_be/domain/user/service/StudentQueryService.kt
  src/main/kotlin/org/example/root_be/domain/week_days/domain/WeekDays.kt
  src/main/kotlin/org/example/root_be/domain/week_days/domain/repository/WeekDaysRepository.kt
  src/main/kotlin/org/example/root_be/domain/week_days/exception/WeekDaysNotFoundException.kt
  src/main/kotlin/org/example/root_be/global/err/exception/ErrorCode.kt
Labels: refactor

#85 chore: (#84) buildSrc
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/DependencyNames.kt
  buildSrc/src/main/kotlin/DependencyVersion.kt
  buildSrc/src/main/kotlin/PluginVersions.kt
Labels: chore
